HISTSIZE=
HISTFILESIZE=
PS1='\[\033[01;32m\]\u\[\033[01;33m\]@\[\033[01;36m\]\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ..="cd .."
source /etc/profile.d/bash_completion.sh
alias mtk-autobuild=~/mtk-openwrt-feeds/autobuild/unified/autobuild.sh
