name: CD for BpiR4Toolchain Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build
      run: docker build -t bpi-r4-toolchain ./docker
    - name: Tags
      run: |
        docker tag bpi-r4-toolchain ${{ secrets.DOCKER_HUB_USER }}/bpi-r4-toolchain:${{ github.sha }}
        docker tag bpi-r4-toolchain ${{ secrets.DOCKER_HUB_USER }}/bpi-r4-toolchain:latest
    - name: Push
      run: |
        docker push ${{ secrets.DOCKER_HUB_USER }}/bpi-r4-toolchain:${{ github.sha }}
        docker push ${{ secrets.DOCKER_HUB_USER }}/bpi-r4-toolchain:latest

